version: '3'
services:
    atlas:
      image: ${ATLAS_IMAGE:-z0beat/atlas:2.1.0}
      restart: always
      ports:
        - 21000:21000
      volumes:
        - ./atlas/scripts/:/docker-init-scripts.d/
        - ./atlas/conf/:/opt/atlas/conf
        - ./atlas/models/:/opt/atlas/models
      depends_on:
        - solr
        - kafka
        - cassandra

    solr:
      image: ${SOLR_IMAGE:-solr:7.7.2}
      restart: always
      ports:
        - 8983:8983
      environment:
        - ZK_HOST=zookeeper:2181/solr
      volumes:
        - ./solr/scripts/:/docker-entrypoint-initdb.d/
        - ./solr/configsets/atlas:/opt/solr/server/solr/configsets/atlas:ro

    zookeeper:
      image: ${ZOOKEEPER_IMAGE:-zookeeper:3.4.14}
      restart: always
      ports:
        - 2181:2181

    kafka:
      image: ${KAFKA_IMAGE:-bitnami/kafka:2.5.0}
      ports:
        - 9092:9092
        - 9093:9093
        - 9094:9094
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_HOST_2:PLAINTEXT
        - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9093,PLAINTEXT_HOST_2://:9094
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093,PLAINTEXT_HOST_2://localhost:9094
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper

    cassandra:
      image: ${CASSANDRA_IMAGE:-cassandra:3.11.6}
      ports:
        - 9042:9042