POST http://localhost:21000/api/atlas/v2/relationship
Authorization: Basic admin admin
Content-Type: application/json

    {
      "name": "spark_table_storagedesc",
      "serviceType": "spark",
      "typeVersion": "1.0",
      "relationshipCategory": "COMPOSITION",
      "endDef1": {
        "type": "spark_table",
        "name": "location",
        "isContainer": true,
        "cardinality": "SINGLE"
      },
      "endDef2": {
        "type": "spark_storagedesc",
        "name": "table2",
        "isContainer": false,
        "cardinality": "SINGLE"
      },
      "propagateTags": "NONE"
    }

###
