version: '3'
services:
    # atlas:
    #   image: atlas:local
    #   restart: always
    #   ports:
    #     - 21000:21000
    #   environment:
    #     KEY: value
    #   depends_on:
    #     - solr
    #     - kafka
    #     - cassandra

    solr:
      image: solr:7.7.2
      ports:
        - 8983:8983
      environment:
        - ZK_HOST=zookeeper:2181/solr
      volumes:
        - ./solr/scripts/00_init_zk.sh:/docker-entrypoint-initdb.d/00_init_zk.sh
      restart: always
      command: solr-precreate atlas

    zookeeper:
      image: zookeeper:3.4.14
      ports:
        - 2181:2181
      restart: always

    # kafka:
    #   image: bitnami/kafka:2.5.0
    #   ports:
    #     - 9092:9092
    #   environment:
    #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #     - ALLOW_PLAINTEXT_LISTENER=yes
    #   depends_on:
    #     - zookeeper
    
    # cassandra:
    #   image: cassandra:3.11.6
    #   ports:
    #     - 9042:9042