version: '3'
services:
    atlas:
      image: atlas:local
      restart: always
      ports:
        - 21000:21000
      volumes:
        - ./atlas/scripts/:/docker-init-scripts.d/
        - ./atlas/conf/:/opt/atlas/conf
      depends_on:
        - solr
        - kafka
        - cassandra

    solr:
      image: solr:7.7.2
      restart: always
      ports:
        - 8983:8983
      environment:
        - ZK_HOST=zookeeper:2181/solr
      volumes:
        - ./solr/scripts/:/docker-entrypoint-initdb.d/
        - ./solr/configsets/atlas:/opt/solr/server/solr/configsets/atlas:ro

    zookeeper:
      image: zookeeper:3.4.14
      restart: always
      ports:
        - 2181:2181

    kafka:
      image: bitnami/kafka:2.5.0
      ports:
        - 9092:9092
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper
    
    cassandra:
      image: cassandra:3.11.6
      ports:
        - 9042:9042