name: Build and Deploy to Dockerhub
on: [push]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: z0beat/atlas
          # tag_with_ref: true
          # push: ${{ startsWith(github.ref, 'refs/tags/') }}
