name: Build and deploy to container registries
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 2.1.0-stretch
            build-args: |
              VERSION=2.1.0
              BUILD_PROFILE=dist
            tags: |
              z0beat/atlas:2.1.0-stretch
              z0beat/atlas:2.1.0
              z0beat/atlas:latest
              ghcr.io/zer0beat/atlas:2.1.0-stretch
              ghcr.io/zer0beat/atlas:2.1.0
              ghcr.io/zer0beat/atlas:latest
            dockerfile: stretch/Dockerfile
          - name: 2.1.0-stretch-dev
            build-args: |
              VERSION=2.1.0
              BUILD_PROFILE=dist|embedded-hbase-solr
            tags: |
              z0beat/atlas:2.1.0-stretch-dev
              z0beat/atlas:2.1.0-dev
              ghcr.io/zer0beat/atlas:2.1.0-stretch-dev
              ghcr.io/zer0beat/atlas:2.1.0-dev
            dockerfile: stretch/Dockerfile
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Prepare environment
        run: git clone https://github.com/docker-library/official-images.git ./official-images

      - name: Pull dependencies
        run: grep FROM ${{ matrix.dockerfile }} | awk 'toupper($1) == "FROM" { print $2 }' | xargs -I {} docker pull {}

      - name: Build ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.build-args }}
          tags: localhost:5000/z0beat/atlas:test
          push: true
      
      - name: Test ${{ matrix.name }}
        run: ./test/run-tests.sh 'z0beat/atlas:test'

      - name: Publish ${{ matrix.name }}
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master'}}
        with:
          tags: ${{ matrix.tags }}
          cache-from: type=registry,ref=z0beat/atlas:test
          cache-to: type=inline
          push: true
